### ISSUE TITLE
python Pyqt configure.py has a error

### ISSUE THREAD

**Issue by mathoyus** [honeynet/apkinspector#15]
Qt Designer plugin disabled because Python library couldn't be found
An internal error occured.  Please report all the output from the program,
including the following traceback, to support@riverbankcomputing.com.
Traceback (most recent call last):
  File "configure.py", line 2272, in <module>
    main()
  File "configure.py", line 2257, in main
    subdirs=pyqt.qpy_libs() + pyqt_modules + xtra_modules + pyqt.tools(),
  File "configure.py", line 962, in tools
    link = "%s -lpython%d.%d%s" % (lib_dir_flag, py_major, py_minor, abi)
UnboundLocalError: local variable 'lib_dir_flag' referenced before assignment
root@ubuntu:~/APKinspector/PyQt-x11-gpl-4.8.4#

**Comment by mathoyus** [comment]
what my python missing ,thanks

**Comment by mathoyus** [comment]
Generating the C++ source for the QtXmlPatterns module...
sip: Deprecation warning: /root/APKinspector/PyQt-x11-gpl-4.8.4/sip/QtCore/qglobal.sip:281: Annotation is invalid
Creating the Makefile for the QtXmlPatterns module...
Generating the C++ source for the QtDesigner module...
sip: Deprecation warning: /root/APKinspector/PyQt-x11-gpl-4.8.4/sip/QtCore/qglobal.sip:281: Annotation is invalid
Creating the Makefile for the QtDesigner module...
Generating the C++ source for the Qt module...
sip: Deprecation warning: /root/APKinspector/PyQt-x11-gpl-4.8.4/sip/QtCore/qglobal.sip:281: Annotation is invalid
Creating the Makefile for the Qt module...
Generating the C++ source for the _qt module...
sip: Deprecation warning: /root/APKinspector/PyQt-x11-gpl-4.8.4/sip/QtCore/qglobal.sip:281: Annotation is invalid
Creating the Makefile for the _qt module...

**Comment by c0d3sling3r** [comment]
I have this problem and it's gonna kill me.. Help!

**Comment by glaslos** [comment]
What version of Python are you using?
How did you install SIP?

**Comment by mathoyus** [comment]
i am already give up,some  component already fail,and no support
